---
- name: Install security packages (Ubuntu)
  package:
    name: libnl-3-dev, libnl-genl-3-dev, unzip
    state: present
    lock_timeout : 180

- name: Running pro status 
  ansible.builtin.shell: "pro status --format yaml | grep -o 'attached: [^,}]*' | awk '{print $2}'"
  register: status

- name: Checking if VM is a registered host
  set_fact: 
    attached: "{{ status.stdout | lower | bool }}"

- name: Attach host to Ubunto Pro Subscription
  when: not attached
  block:
    - name: running pro attach <token>
      ansible.builtin.command: "pro attach {{ ubuntu_pro_token }}"
      vars:
        ubuntu_pro_token: "{{ upro_token }}"

    - name: Checking host registration update
      ansible.builtin.shell: "pro status --format yaml | grep -o 'attached: [^,}]*' | awk '{print $2}'"
      register: updated_status

    - name: Verifying registration
      set_fact: 
        updated_attachment: "{{ updated_status.stdout | lower | bool }}"
      failed_when: not updated_attachment
